# Render service definition (example)
services:
  - type: web
    name: hk-bus-eta-proxy
    env: python
    plan: free
    repo: <your-github-username>/bus_eta_proxy
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
